image_transport: 'raw'    # формат изображения (raw - без обработки)
family: '36h11'           # семейство тегов (в данном случае tag36h11)
size: 0.162                # стандартный размер тега в метрах (16 см)
threads: 4                # количество потоков для обработки
max_hamming: 0            # максимально допустимое расстояние Хэмминга (исправленные биты)
z_up: true                # поворот по оси X, чтобы ось Z смотрела вверх

decimate: 0.0             # уменьшение разрешения для детектирования квадратов (0.0 - отключено)
blur: 1.0                 # размытие по Гауссу (sigma) для детектирования квадратов
refine-edges: 1           # точное позиционирование по градиентам (1 - включено)
debug: 0                  # сохранение отладочных изображений в рабочую директорию (0 - отключено)
